version: 2
jobs:
  build:
    working_directory: ~/deps

    docker:
      - image: docker:20.10.14-git

    environment:
      VERSION: "1.1.0"
      TAG: "1.1.0-alpine"
      # TAG: ${VERSION}-alpine
      # TAG_MINOR: ${VERSION%.*}-alpine
      # TAG_MAJOR: ${VERSION%%.*}-alpine 
      # BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
      VCS_REF: ${CIRCLE_SHA1}
      BATS_VER: "0.4.0"  

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14

      # - run:
      #     name: set TAG vars
      #     command: |
      #       export TAG=${VERSION}-alpine
      #       export TAG_MINOR=${VERSION%.*}-alpine
      #       export TAG_MAJOR=${VERSION%%.*}-alpine           

      - run:
          name: install dependencies - lib
          command: |
            apk --no-cache add \
              bash \
              curl \
              curl-dev \
              make 
              # python3 
            
            # pip3 install --upgrade pip
            # pip3 install docker-compose==1.9.0

      - run:
          name: install dependencies - bats
          command: |
            dir=${CIRCLE_WORKING_DIRECTORY}
            mkdir -p ${dir}

            if [[ ! -e ${dir}/bats_v${BATS_VER}.tar.gz ]]; then 
              curl -sSL -o ${dir}/bats_v${BATS_VER}.tar.gz https://github.com/sstephenson/bats/archive/v${BATS_VER}.tar.gz
            fi
            
            tar -xf ${dir}/bats_v${BATS_VER}.tar.gz
            bats-${BATS_VER}/install.sh /usr/local

      - run:
          name: docker client and remote info
          command: |
            docker version
            docker info

      - run:
          name: docker image build
          command: make all

      - run:
          name: test
          command: |
            docker inspect smizy/scikit-learn:${TAG}
            make test

      - run:
          name: docker image push
          command: |

            TAG_MINOR=$(echo $VERSION | cut -d. -f1-2)-alpine
            TAG_MAJOR=$(echo $VERSION | cut -d. -f1)-alpine

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            
            docker image tag smizy/scikit-learn:${TAG} smizy/scikit-learn
            docker image push smizy/scikit-learn:${TAG}

            docker image tag smizy/scikit-learn:${TAG} smizy/scikit-learn:${TAG_MINOR}
            docker image push smizy/scikit-learn:${TAG_MINOR}

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker image push smizy/scikit-learn:latest
            fi
            
            docker logout
